import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProviders } from "../components/ui/providers/providers";
import AuthProvider from "@/components/ui/providers/authProvider";
import { cn } from "@/lib/utils";
import ProfileProvider from "@/components/ui/providers/profileProvider";
import ClientSessionWrapper from "@/components/ui/providers/clientSessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientSessionWrapper>
      <AuthProvider>
        <html lang="en" suppressHydrationWarning>
          <body
            className={cn(
              `${geistSans.variable} ${geistMono.variable} antialiased`,
              "min-h-screen"
            )}
          >
            <ThemeProviders>
              <ProfileProvider>{children}</ProfileProvider>
            </ThemeProviders>
          </body>
        </html>
      </AuthProvider>
    </ClientSessionWrapper>
  );
}
